"""OBSIDIAN — Generated patch model."""

from __future__ import annotations

from enum import Enum as PyEnum

from sqlalchemy import Boolean, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.database import Base


class PatchStatus(str, PyEnum):
    """Patch lifecycle status."""
    GENERATED = "generated"
    TESTING = "testing"
    VERIFIED = "verified"
    APPLIED = "applied"
    REJECTED = "rejected"
    FAILED = "failed"


class Patch(Base):
    """A code patch generated by the Auto Patcher agent."""

    __tablename__ = "patches"

    # Parent scan
    scan_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("scans.id"), index=True
    )
    scan: Mapped["Scan"] = relationship(back_populates="patches")  # noqa: F821

    # Target
    file_path: Mapped[str] = mapped_column(String(500))
    finding_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("findings.id"), nullable=True
    )

    # Patch content
    original_code: Mapped[str] = mapped_column(Text)
    patched_code: Mapped[str] = mapped_column(Text)
    diff: Mapped[str] = mapped_column(Text)  # unified diff format
    explanation: Mapped[str] = mapped_column(Text)

    # Verification
    status: Mapped[PatchStatus] = mapped_column(
        Enum(PatchStatus), default=PatchStatus.GENERATED
    )
    tests_passed: Mapped[bool] = mapped_column(Boolean, default=False)
    tests_generated: Mapped[int] = mapped_column(Integer, default=0)
    test_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    verification_output: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Confidence
    confidence_score: Mapped[float] = mapped_column(default=0.0)
